[package]
  cjc-version = "1.0.3"
  name = "effects"
  description = "nothing here"
  version = "1.0.0"
  target-dir = ""
  src-dir = ""
  output-type = "static"
  compile-option = ""
  override-compile-option = ""
  link-option = ""
  package-configuration = {}

[dependencies]

[target.aarch64-apple-darwin]
  [target.aarch64-apple-darwin.bin-dependencies]
    path-option = ["${CANGJIE_HOME}/runtime/lib/darwin_aarch64_cjnative"]
